### ISSUE TITLE
Navbar wont show on games page

### ISSUE THREAD

**Issue by accessgames** [Command-Enterprises/Commander#10]
The top Nav Bar wont show on the games tab. I could put the raw html code instead of the navbar fetch script @Command-Enterprises/commander-developers

**Comment by qwertychomp** [comment]
fixed by my pull request #12 , pls merge (actually merge, dont just copy everything in the pull request and commit it yourself)
it turns out that navbar.html hadnt been updated in a while, so it was different from the navbar that index.css expects
