### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by CalebHacks** [Command-Enterprises/Commander#27]
Proxy doesn't work

**Comment by PaytonsSins** [comment]
![Screenshot 2024-01-23 12 16 58 PM](https://github.com/Command-Enterprises/Commander/assets/125277897/05d0f195-7d4e-49bb-85a0-d9e07251d52c)

**Comment by Quartinal** [comment]
@CalebHacks and @PaytonsSins, Commander is still a work in progress (sort of a beta). We're also trying to develop our own proxy. We'll keep you guys updated 💯

**Comment by qwertychomp** [comment]
im working on writing the actual proxy part of commander proxy (it will hopefully be working soon!)

**Comment by accessgames** [comment]
Its working now :)

**Comment by PaytonsSins** [comment]
> Its working now :)

Appreciate it
