### ISSUE TITLE
Make the proxy work

### ISSUE THREAD

**Issue by PrestonT500** [Command-Enterprises/Commander#7]
The iframe does not unblock sites

**Comment by PrestonT500** [comment]
I think i figured it out, maybe

**Comment by PrestonT500** [comment]
nevermind

**Comment by harveyay** [comment]
U mean the games or proxy?

**Comment by PrestonT500** [comment]
Everything

**Comment by PrestonT500** [comment]
Ill try the /service/ thing

**Comment by harveyay** [comment]
The games dont need it cuz u can just use an unblocked site. Although the proxy will need something other than an iframe, it isn't even built yet.

**Comment by Quartinal** [comment]
@PrestonT500 and @harveyay, iframes are really slow on hosting platforms like Vercel. Maybe use GZIP or Brotli Compression with Nginx❔ But I recommend using Nginx on (Fedora) Linux, as that will make Commander have better performance, security, and scalability.

**Comment by harveyay** [comment]
Should we use CMD+Search in the proxy, im assuming we will

**Comment by Quartinal** [comment]
Yes, we should, it would be a lot better. Diffs <3

**Comment by accessgames** [comment]
bruh this is dead no one talks on it anymore

**Comment by accessgames** [comment]
It doesn't look like we are making a proxy any time soon so as a short term fix, we could embed a proxy I found into the website. Check it out https://pro2.minoa.cat/?link=aHR0cHM6Ly93d3cuZ29vZ2xlLmNvbS8%3D

**Comment by qwertychomp** [comment]
im working on a proxy in nodejs, i might have it working in a month or two

**Comment by accessgames** [comment]
Ok. I have embedded the proxy for now but when its done we'll use yours
